-- V1: schema inicial gerado a partir do DDL esperado pelo Hibernate/PostgreSQL.
-- Fonte: Hibernate ORM contra PostgreSQL 14 descartável, revisado para execução via Flyway.





SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;







SET default_tablespace = '';

SET default_table_access_method = heap;


CREATE TABLE public.cargos (
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    id_cargo bigint NOT NULL,
    nome_cargo character varying(255) NOT NULL
);



ALTER TABLE public.cargos ALTER COLUMN id_cargo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cargos_id_cargo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.contrato_equipe (
    contrato_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    id_equipe bigint NOT NULL,
    usuario_id bigint NOT NULL,
    funcao_na_equipe character varying(100)
);



ALTER TABLE public.contrato_equipe ALTER COLUMN id_equipe ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contrato_equipe_id_equipe_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.contratos (
    data_fim date,
    data_inicio date,
    prazo_execucao date,
    analista_responsavel_id bigint,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    id_contrato bigint NOT NULL,
    proposta_id bigint NOT NULL,
    status character varying(50)
);



ALTER TABLE public.contratos ALTER COLUMN id_contrato ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contratos_id_contrato_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.documentos (
    validado boolean,
    analista_id bigint,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    empresa_id bigint NOT NULL,
    id_documento bigint NOT NULL,
    proposta_id bigint,
    tipo_documento character varying(100),
    url character varying(1000)
);



ALTER TABLE public.documentos ALTER COLUMN id_documento ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documentos_id_documento_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.empresa_servico (
    id_empresa bigint NOT NULL,
    id_servico bigint NOT NULL
);



CREATE TABLE public.empresas (
    uf character varying(2),
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    id_empresa bigint NOT NULL,
    cep character varying(10),
    representante_cpf character varying(14),
    bairro character varying(255),
    cidade character varying(255),
    cnpj character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    logradouro character varying(255),
    nome_fantasia character varying(255),
    numero character varying(255),
    razao_social character varying(255) NOT NULL,
    representante_contato character varying(255),
    representante_nome character varying(255),
    telefone character varying(255)
);



ALTER TABLE public.empresas ALTER COLUMN id_empresa ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.empresas_id_empresa_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.notificacoes (
    created_at timestamp(6) without time zone,
    data_envio timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    id_notificacao bigint NOT NULL,
    id_usuario bigint NOT NULL,
    tipo character varying(50),
    mensagem character varying(1000) NOT NULL
);



ALTER TABLE public.notificacoes ALTER COLUMN id_notificacao ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notificacoes_id_notificacao_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.participantes_reuniao (
    id_reuniao bigint NOT NULL,
    id_usuario bigint NOT NULL
);



CREATE TABLE public.permissoes (
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    id_permissao bigint NOT NULL,
    descricao character varying(255) NOT NULL
);



ALTER TABLE public.permissoes ALTER COLUMN id_permissao ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permissoes_id_permissao_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.planilhas (
    bloqueada boolean,
    contrato_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    id_planilha bigint NOT NULL,
    permissao_visualizacao character varying(100),
    url_google_sheets character varying(1000)
);



ALTER TABLE public.planilhas ALTER COLUMN id_planilha ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.planilhas_id_planilha_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.propostas (
    analista_responsavel_id bigint,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    empresa_id bigint NOT NULL,
    id_proposta bigint NOT NULL,
    usuario_id bigint NOT NULL,
    status character varying(50),
    CONSTRAINT propostas_status_check CHECK (((status)::text = ANY ((ARRAY['RECEIVED'::character varying, 'IN_TRIAGE'::character varying, 'ELIGIBLE'::character varying, 'PENDING_ADJUSTMENTS'::character varying, 'COMMERCIAL_PROPOSAL'::character varying, 'COMMERCIAL_PROPOSAL_APPROVED'::character varying, 'COMMERCIAL_PROPOSAL_REJECTED'::character varying, 'READY_FOR_NEXT_STAGE'::character varying])::text[])))
);



ALTER TABLE public.propostas ALTER COLUMN id_proposta ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.propostas_id_proposta_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.refresh_tokens (
    expiry_date timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    token character varying(255) NOT NULL
);



ALTER TABLE public.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.relatorios (
    contrato_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    data_envio timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    id_relatorio bigint NOT NULL,
    revisor_id bigint,
    status character varying(50),
    url_pdf character varying(1000),
    CONSTRAINT relatorios_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'IN_REVIEW'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);



ALTER TABLE public.relatorios ALTER COLUMN id_relatorio ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.relatorios_id_relatorio_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.requisitos_documentais (
    prazo date,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    documento_id bigint,
    id_requisito_documental bigint NOT NULL,
    proposta_id bigint NOT NULL,
    validado_em timestamp(6) without time zone,
    validado_por_id bigint,
    status character varying(50) NOT NULL,
    tipo_documento character varying(100) NOT NULL,
    motivo_reprovacao character varying(2000),
    CONSTRAINT requisitos_documentais_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SUBMITTED'::character varying, 'NON_COMPLIANT'::character varying, 'APPROVED'::character varying])::text[]))),
    CONSTRAINT requisitos_documentais_tipo_documento_check CHECK (((tipo_documento)::text = ANY ((ARRAY['BALANCO_PATRIMONIAL'::character varying, 'DRE'::character varying, 'CONTRATO_SOCIAL'::character varying, 'CNPJ'::character varying, 'PLANILHA_GERENCIAL'::character varying])::text[])))
);



ALTER TABLE public.requisitos_documentais ALTER COLUMN id_requisito_documental ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.requisitos_documentais_id_requisito_documental_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.reunioes (
    data date,
    hora time(0) without time zone,
    hora_fim time(0) without time zone,
    presencial boolean,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    empresa_id bigint NOT NULL,
    id_reuniao bigint NOT NULL,
    status character varying(50),
    local character varying(500),
    pauta character varying(2000),
    titulo character varying(255) NOT NULL
);



ALTER TABLE public.reunioes ALTER COLUMN id_reuniao ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reunioes_id_reuniao_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.servicos (
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    id_servico bigint NOT NULL,
    nome character varying(255) NOT NULL
);



ALTER TABLE public.servicos ALTER COLUMN id_servico ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.servicos_id_servico_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.usuario_permissoes (
    id_permissao bigint NOT NULL,
    id_usuario bigint NOT NULL
);



CREATE TABLE public.usuarios (
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    id_usuario bigint NOT NULL,
    cpf character varying(14) NOT NULL,
    contato character varying(50),
    senha_hash character varying(60),
    google_refresh_token character varying(1000),
    cargo character varying(255),
    email character varying(255) NOT NULL,
    nome_completo character varying(255) NOT NULL,
    situacao character varying(255),
    CONSTRAINT usuarios_cargo_check CHECK (((cargo)::text = ANY ((ARRAY['COMPLIANCE'::character varying, 'CEO'::character varying, 'MEMBRO_CONSELHO'::character varying, 'CSO'::character varying, 'CMO'::character varying, 'CFO'::character varying, 'CONTADOR'::character varying, 'ANALISTA_CHEFE'::character varying, 'ANALISTA_SENIOR'::character varying, 'ANALISTA'::character varying, 'ANALISTA_VI_TRAINEE'::character varying, 'ANALISTA_VI_JUNIOR'::character varying, 'ANALISTA_VI_PLENO'::character varying, 'ANALISTA_VI_SENIOR'::character varying, 'ANALISTA_BPO_FINANCEIRO'::character varying])::text[])))
);



ALTER TABLE public.usuarios ALTER COLUMN id_usuario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_usuario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY public.cargos
    ADD CONSTRAINT cargos_pkey PRIMARY KEY (id_cargo);



ALTER TABLE ONLY public.contrato_equipe
    ADD CONSTRAINT contrato_equipe_pkey PRIMARY KEY (id_equipe);



ALTER TABLE ONLY public.contratos
    ADD CONSTRAINT contratos_pkey PRIMARY KEY (id_contrato);



ALTER TABLE ONLY public.documentos
    ADD CONSTRAINT documentos_pkey PRIMARY KEY (id_documento);



ALTER TABLE ONLY public.empresa_servico
    ADD CONSTRAINT empresa_servico_pkey PRIMARY KEY (id_empresa, id_servico);



ALTER TABLE ONLY public.empresas
    ADD CONSTRAINT empresas_pkey PRIMARY KEY (id_empresa);



ALTER TABLE ONLY public.notificacoes
    ADD CONSTRAINT notificacoes_pkey PRIMARY KEY (id_notificacao);



ALTER TABLE ONLY public.participantes_reuniao
    ADD CONSTRAINT participantes_reuniao_pkey PRIMARY KEY (id_reuniao, id_usuario);



ALTER TABLE ONLY public.permissoes
    ADD CONSTRAINT permissoes_pkey PRIMARY KEY (id_permissao);



ALTER TABLE ONLY public.planilhas
    ADD CONSTRAINT planilhas_pkey PRIMARY KEY (id_planilha);



ALTER TABLE ONLY public.propostas
    ADD CONSTRAINT propostas_pkey PRIMARY KEY (id_proposta);



ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_token_key UNIQUE (token);



ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_user_id_key UNIQUE (user_id);



ALTER TABLE ONLY public.relatorios
    ADD CONSTRAINT relatorios_pkey PRIMARY KEY (id_relatorio);



ALTER TABLE ONLY public.requisitos_documentais
    ADD CONSTRAINT requisitos_documentais_pkey PRIMARY KEY (id_requisito_documental);



ALTER TABLE ONLY public.reunioes
    ADD CONSTRAINT reunioes_pkey PRIMARY KEY (id_reuniao);



ALTER TABLE ONLY public.servicos
    ADD CONSTRAINT servicos_pkey PRIMARY KEY (id_servico);



ALTER TABLE ONLY public.usuario_permissoes
    ADD CONSTRAINT usuario_permissoes_pkey PRIMARY KEY (id_permissao, id_usuario);



ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id_usuario);



ALTER TABLE ONLY public.documentos
    ADD CONSTRAINT fk1cv92xv6tlh4as1obukbi81o2 FOREIGN KEY (analista_id) REFERENCES public.usuarios(id_usuario);



ALTER TABLE ONLY public.contrato_equipe
    ADD CONSTRAINT fk22q20nw92t9fbrv61esh2y7s8 FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id_usuario);



ALTER TABLE ONLY public.requisitos_documentais
    ADD CONSTRAINT fk31ntpmf3gpbv9o9nlq19tbg3l FOREIGN KEY (proposta_id) REFERENCES public.propostas(id_proposta);



ALTER TABLE ONLY public.usuario_permissoes
    ADD CONSTRAINT fk3nqi24xijn664n7imr1iunbsl FOREIGN KEY (id_permissao) REFERENCES public.permissoes(id_permissao);



ALTER TABLE ONLY public.reunioes
    ADD CONSTRAINT fk43lyw8mwlc4btgemc9vjaxkax FOREIGN KEY (empresa_id) REFERENCES public.empresas(id_empresa);



ALTER TABLE ONLY public.requisitos_documentais
    ADD CONSTRAINT fk5xar9a1wmikj0b83fw5vlvy5y FOREIGN KEY (documento_id) REFERENCES public.documentos(id_documento);



ALTER TABLE ONLY public.empresa_servico
    ADD CONSTRAINT fk73bsw3f2m61rmx2b0c7jc1ju0 FOREIGN KEY (id_servico) REFERENCES public.servicos(id_servico);



ALTER TABLE ONLY public.documentos
    ADD CONSTRAINT fk8kh0g3vhymbe33a3jurgxdhnd FOREIGN KEY (empresa_id) REFERENCES public.empresas(id_empresa);



ALTER TABLE ONLY public.relatorios
    ADD CONSTRAINT fk9dkcip3a4nniexxytex59403f FOREIGN KEY (revisor_id) REFERENCES public.usuarios(id_usuario);



ALTER TABLE ONLY public.requisitos_documentais
    ADD CONSTRAINT fk9jowuct6q97flogcec8820woo FOREIGN KEY (validado_por_id) REFERENCES public.usuarios(id_usuario);



ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk9o75y2asbyt9vk8geeicfu72e FOREIGN KEY (user_id) REFERENCES public.usuarios(id_usuario);



ALTER TABLE ONLY public.participantes_reuniao
    ADD CONSTRAINT fk9qgxv886ajmyggppvcuoyl19 FOREIGN KEY (id_reuniao) REFERENCES public.reunioes(id_reuniao);



ALTER TABLE ONLY public.usuario_permissoes
    ADD CONSTRAINT fka88vqv7ho0dhargqlr8a8olih FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario);



ALTER TABLE ONLY public.propostas
    ADD CONSTRAINT fkays7elevljosmoa0546ue6bgd FOREIGN KEY (empresa_id) REFERENCES public.empresas(id_empresa);



ALTER TABLE ONLY public.contrato_equipe
    ADD CONSTRAINT fkc51phgjsw07gfj2dm8rpdn1bi FOREIGN KEY (contrato_id) REFERENCES public.contratos(id_contrato);



ALTER TABLE ONLY public.contratos
    ADD CONSTRAINT fkdk4uads04inid42aeg1mgo1vl FOREIGN KEY (proposta_id) REFERENCES public.propostas(id_proposta);



ALTER TABLE ONLY public.propostas
    ADD CONSTRAINT fkhilj4edalco0yujwggjc6ytfa FOREIGN KEY (analista_responsavel_id) REFERENCES public.usuarios(id_usuario);



ALTER TABLE ONLY public.documentos
    ADD CONSTRAINT fkjjweiy23shjfnkex7f34vy9j0 FOREIGN KEY (proposta_id) REFERENCES public.propostas(id_proposta);



ALTER TABLE ONLY public.notificacoes
    ADD CONSTRAINT fkk85kaie5ogbiu3im7hurhg3vr FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario);



ALTER TABLE ONLY public.relatorios
    ADD CONSTRAINT fkl97ar3efr7qjaxk9ys5cmp3se FOREIGN KEY (contrato_id) REFERENCES public.contratos(id_contrato);



ALTER TABLE ONLY public.planilhas
    ADD CONSTRAINT fknd6j7hfe9xg2lrt4wdmqtck0m FOREIGN KEY (contrato_id) REFERENCES public.contratos(id_contrato);



ALTER TABLE ONLY public.empresa_servico
    ADD CONSTRAINT fkovbtx92njs4f1qkq19u1u4d3m FOREIGN KEY (id_empresa) REFERENCES public.empresas(id_empresa);



ALTER TABLE ONLY public.contratos
    ADD CONSTRAINT fkrp94h756nf9u1cf0blj8pcp5v FOREIGN KEY (analista_responsavel_id) REFERENCES public.usuarios(id_usuario);



ALTER TABLE ONLY public.participantes_reuniao
    ADD CONSTRAINT fktaiqk09ml26bqvqlm0jefh5ng FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario);



ALTER TABLE ONLY public.propostas
    ADD CONSTRAINT fktrfg7ul9jh9047x7j9wnv6gmr FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id_usuario);




